### ISSUE TITLE
Cheat doesn't work on the latest Windows 11 Insider build

### ISSUE THREAD

**Issue by wizpizz** [FarmEquipment69/FlyingGuys#1]
~Even though my Windows Defender is completely turned off, the driver still fails to load. Maybe it doesn't support Windows 11?~

<img width="660" alt="FlyingGuys_3aichS4lt2" src="https://user-images.githubusercontent.com/76851476/182800301-3be390db-b6be-4971-b2d3-c6aa9c652a3f.png">

Edit: Seems like v1.0 works fine but 1.0.1 doesn't. Probably caused by secondary driver loading method

Edit 2: v1.0 injects but features do not work. + I don't think the memory addresses are supposed to be 0s
![image](https://user-images.githubusercontent.com/76851476/182830903-06bea592-7bb8-45e0-a29f-aca167369998.png)

**Comment by FarmEquipment69** [comment]
Hi,

It will work on most versions of Windows 11 just not the latest insider i believe? Its an issue with the Vulnerable Intel driver KDMapper uses being revoked in the newest build. More info here https://github.com/TheCruZ/kdmapper/issues/65

I am currently working on a new version that will fix this but there is no ETA at the moment.

**Comment by oenderg** [comment]
Ah that explains it then, I am on the latest insider beta build (22622.450)
Thanks for the clarification :)

You can close the issue if you want ^
