### ISSUE TITLE
got banned

### ISSUE THREAD

**Issue by AtomicBool** [FarmEquipment69/FlyingGuys#18]
i used kdu to mapping it
There are no messages from the console(kdu)
and after running flyingguys.exe it said that inject successful
it doesnt work and i got baned after 2-3 match

cpu Amd Ryzen3700x
used ’kdu.exe -prv 11 -map flyingguys.sys‘
i have installed msi dragon center and my gpu is from msi

**Comment by nickythegreaty** [comment]
its a malware, AND it gets you banned? wow.
