### ISSUE TITLE
Not working now

### ISSUE THREAD

**Issue by helixlord** [FarmEquipment69/FlyingGuys#2]

**Comment by FarmEquipment69** [comment]
What version & build of Windows are you running? Make sure you are using the latest version v1.0.1 and not the older first release.

**Comment by helixlord** [comment]
Im using v1.0.1
the menu opens in the game, but the functions do not work :(

**Comment by helixlord** [comment]
21H2 19044.1826

**Comment by helixlord** [comment]
Will you release a new version?

**Comment by Fendi1211** [comment]
I have windows 10 and even though my windows defender is completely disabled, the driver still won't load.

**Comment by FarmEquipment69** [comment]
Please upload a screenshot of the command prompt/terminal window after launching FlyingGuys.exe

**Comment by Yumesaka13** [comment]
![Snipaste_2022-08-20_00-08-37](https://user-images.githubusercontent.com/79508714/185661231-f0cfafa4-c991-4021-a968-973e19763f1a.png)
I can Open the window but the functions can't work.

**Comment by Yumesaka13** [comment]
i am on Steam version.
it built by my self.

**Comment by Yumesaka13** [comment]
im on windows 11 21h2

**Comment by FarmEquipment69** [comment]
New version released - Use only the epic version and not steam
