### ISSUE TITLE
Not Working For Me

### ISSUE THREAD

**Issue by Basgsar10** [FarmEquipment69/FlyingGuys#3]
First version injects but the cheat doesn't work and the lastest version can't load the driver.
I have Windows SDK and WDK installed.
Windows 10 v21H2
CPU: AMD Ryzen 3600X
GPU: AMD RX 5700 XT
Kaspersky and Avast fully turned off.

**Comment by TianaJ3** [comment]
If you are using Steam, you can solve it by using the Epic Game Launcher ^^ If it was helpful, please accept the question

**Comment by TianaJ3** [comment]
> First version injects but the cheat doesn't work and the lastest version can't load the driver. I have Windows SDK and WDK installed. Windows 10 v21H2 CPU: AMD Ryzen 3600X GPU: AMD RX 5700 XT Kaspersky and Avast fully turned off.

If you are using Steam, you can solve it by using the Epic Game Launcher ^^ If it was helpful, please accept the question!!
